config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resource :like, only: [:create, :destroy], controller: 'likes'
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :destroy, Post, author_id: user.id
      can :destroy, CommentEntry, users_id: user.id
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  /**an empty model**/
end

app/models/comment_entry.rb
class CommentEntry < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_create :update_post_comments_counter

  def update_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/like_entry.rb
class LikeEntry < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  validates :author, presence: true
  validates :post, presence: true

  after_create :update_post_likes_counter

  private

  def update_post_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :comment_entries, dependent: :destroy
  has_many :likes, class_name: 'LikeEntry', dependent: :destroy

  validates :author, presence: true
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_create :update_user_post_counter

  attribute :content, :text

  def five_recent_comments
    comment_entries.order(created_at: :desc).limit(5)
  end

  private

  def update_user_post_counter
    author.increment!(:post_counter) if author.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comment_entries, foreign_key: 'author_id', dependent: :destroy
  has_many :like_entries, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :three_recent_posts, ->(user) { user.posts.order(created_at: :desc).limit(3) }

  attribute :post_counter, :integer, default: 0

  # def all_posts_with_comments
  #   posts.includes(:comment_entries).order(created_at: :desc)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo email password password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = @post.comment_entries.build
  end

  def create
    @comment = CommentEntry.new(comment_params)
    @comment.author = current_user
    @post = Post.find(params[:post_id])
    @comment.post = @post

    if @comment.save
      cookie[:comment_id] = @comment.id
      redirect_to "/users/#{current_user.id}/posts/#{@post.id}"
    else
      render :new, status: 422
    end
  end

  private

  def comment_params
    params.require(:comment_entry).permit(:text)
  end

  def destroy
    @comment = CommentEntry.find(params[:id])
    authorize! :destroy, @comment
    # Delete the comment logic
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like_entry = LikeEntry.new
    @like_entry.author = current_user
    @like_entry.post_id = params[:post_id]

    if @like_entry.save
      redirect_to(request.referrer || root_path)
    else
      render :new, status: 422
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:comment_entries).all
  end

  def show
    @post = Post.includes(:comment_entries).find(params[:id])
    @user = @post.author
    @comments = @post.comment_entries
    @comment = CommentEntry.new
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.build
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)

    if @post.save
      cookie[:post_id] = @post.id
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    # Delete the post logic
  end
  
  # def destroy
  #   @post.destroy
  #   redirect_to posts_path, notice: 'Post was successfully deleted.'
  # end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.posts.order(created_at: :desc).limit(5)
    cookies[:user_id] = @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<% if can?(:destroy, comment) %>
  <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/comments/new.html.erb
<h1>Add New Comment</h1>

<% if @comment.errors.any? %>
  <div class="comment-errors-box">
    <p><%= pluralize(@comment.errors.count, "error") %> found:</p>

    <ul class="comment-errors-ul">
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [@user, @post, @comment], url: user_post_comments_path(@user, @post) do |form| %>
  <%= form.label :text, 'Input Comment' %>
  <%= form.text_field :text %>
  <br />
  <%= form.submit 'Create Comment entry' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<%= render 'shared/user_card', user: @user %>

<% @user.posts.each_with_index do |post, index| %>
  <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
    <div class="container recent_post">
      <p class="post-num"><%= post.title %></p>
      <p class="post-title"><%= post.text %></p>
      <small class="counters">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></small>

      <% if post.five_recent_comments.length.positive? %>
        <div class="comment-card">
          <h3>Comments</h3>
          <% post.five_recent_comments.each do |comment| %>
            <p><%= comment.author.name %>: <%= comment.text %> </p>
          <% end %>
        </div>
      <% end %>
    </div>
  </a>
<% end %>

<button>Pagination</button>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<%= form_with(model: @post, url: new_user_post_path(@user)) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :content %>
  <%= form.text_area :content %>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<div class="detailed-post-box container">
  <div class="username-and-counters">
    <p class="dp-username"><%= @post.title %> by <%= @user.name %></p>
    <small class="dp-counters">Comments: <%= @post.comment_entries.length %>, Likes: <%= @post.likes_counter %></small>
  <% if can?(:destroy, @post) %>
  <%= button_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
  </div>

  <p class="dp-text"><%= @post.text %></p>

  <%= render 'shared/like' %>
  <a href="/users/<%= @user.id %>/posts/<%= @post.id %>/comments/new" class="add-comment-box">Add a comment</a>

  <div class="dp-comments comment-card">
    <h3>Comments</h3>
    <% if @post.comment_entries.any? %>
      <ul>
        <% @post.comment_entries.each do |comment| %>
          <li><%= comment.text %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No comments yet.</p>
    <% end %>
  </div>
</div>

app/views/shared/_like.html.erb
<%= form_with model: @like_entry, url: user_post_like_path(params[:user_id], params[:id]) do |form| %>
    <%= form.submit "Like" %>
  <% end %>
  

app/views/shared/_user_card.html.erb
<div class="user-card container">
  <div class="user-photo-box">
    <img src=<%= user.photo %> alt="User photo" class="user-photo">
  </div>
  <div class="user-details">
    <h3 class="user-name"><%= user.name %></h3>
    <small>Number of posts: <%= user.posts.length %></small>
  </div>
</div>

app/views/users/index.html.erb
<h1>Here is a list of all users:</h1>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<% @users.each_with_index do |user, index| %>
    <a href="users/<%= user.id %>" class="home-card"><%= render 'shared/user_card', user: user%></a>
  <% end %>

app/views/users/show.html.erb
<h1>User Details</h1>
<%= render partial: 'shared/user_card', locals: { user: @user } %>
<div class="bio-card container">
  <h3 class="bio-card-header">Bio</h3>
  <p><%= @user.bio %> </p>
</div>

<div id="posts">
  <% @recent_posts.each_with_index do |post, index| %>
    <a href="/users/<%= @user.id %>/posts/<%= post.id %>">
      <div class="container recent_post">
        <p class="post-num">Post #<%= index + 1 %></p>
        <p class="post-title"><%= post.title %></p>
        <p class="post-text"><%= post.text %></p> <!-- Add this line to display the post text -->
        <small class="counters">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></small>
      </div>
    </a>
  <% end %>
</div>


<div class="btn-div">
  <a href="/users/<%= @user.id %>/posts" class="see-all-posts">See all posts</a>
</div>